# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae7e9a6773f0a348f53d79b86ff86343d8853d0fd9171070b78fc1b4c58ca24ec52f3ca46c078ae2e2c57bea5f50e6299458965f8391a4259f1f5238e1b830df

test:
  secret_key_base: 5409f8fbdfc862a895696d2a5f8ec3406914284329525c9408cb8790185e4aafa1e5eb03b8ed761c96a69973eae28e426444040044fd3be025527a114b5a10fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
